-- utilisez ce script pour initialiser votre BD --
CREATE DATABASE CogitoBoard;
USE CogitoBoard;

CREATE TABLE tache (
    id VARCHAR(36) PRIMARY KEY,
    titre VARCHAR(100) NOT NULL,
    description TEXT,
    priorite ENUM('LOW', 'MEDIUM', 'HIGH') DEFAULT 'MEDIUM',
    statut ENUM('TODO', 'IN_PROGRESS', 'DONE') DEFAULT 'TODO',
    creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    miseajour TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sousTache (
    id VARCHAR(36) PRIMARY KEY,
    tacheMere VARCHAR(36) NOT NULL,
    titre VARCHAR(100) NOT NULL,
    terminee BOOLEAN DEFAULT FALSE,
    creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    miseajour TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tacheMere) REFERENCES tache(id) ON DELETE CASCADE
);